package com.faraid.model;

public enum HeirType {
    HUSBAND, WIFE, SON, DAUGHTER, FATHER, MOTHER,
    GRANDSON, GRANDDAUGHTER,
    FULL_BROTHER, FULL_SISTER,
    PATERNAL_BROTHER, PATERNAL_SISTER,
    MATERNAL_BROTHER, MATERNAL_SISTER,
    GRANDFATHER, GRANDMOTHER,
    PATERNAL_GRANDFATHER, PATERNAL_GRANDMOTHER,
    MATERNAL_GRANDMOTHER
}